[data]
data_url="https://raw.githubusercontent.com/ervalinskas/public_datasets/main/vin_decoder/raw_data.csv"
raw_data_dir="./data/raw"
validated_data_dir="./data/data_validation"
preprocessed_labels_dir="./data/preprocessed_labels"

[logs]
logs_dir="./logs"

[mlflow]
model_registry="./stores/model"
blob_store="./stores/blob"

[modeling]
vectorizer = { ngram_range=[2, 2], analyzer="char" }

[modeling.hyperparameters]
objective = "multi:softprob"
eval_metric = "accuracy"
param_grid = { learning_rate=[0.1, 0.13, 0.15], depth=[6, 8, 10] }